apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: jlixsopes1p2
  name: consumer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
